"""Copy of FinalPrep_Part1_ToStudent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ty5k_FUw7s8rJQXfekSKRAoc5X3oz8iG

# Final Preparation Part1
Objective: 


*   Lecture1: Data Type
*   Lecture2: String, List
*   Lecture3: If-Else
*   Lecture4: Loop

**Question 1** (3.5 marks). Write a program in which you need to remove the duplicate numbers from a list, which can be pre-defined. The list shown in the image below is just an example. Your output should be displayed in descending order as follows:
a = [1,9,2,3,4,5,5,3,2,4,6,1,9,9,3]
output = [9,6,5,4,3,2,1]
"""

#Q1 Write your program here.
a = [1,9,2,3,4,5,5,3,2,4,6,1,9,9,3]
out = []
for i in a :
  if i not in out :
    out.append(i)
print(sorted(out)[::-1])

"""**Question 2** (3.5 Marks): Write a program in which you need to display the current numbers, previous numbers, and the sum values (the current number + the previous number) as shown in the image below. The current number should start from 1 while the previous number is 0. In this iteration, your current number should not exceed 9. 
Printing current and previous numbers and their sum in a range of 9
Current Number 1 Previous Number 0 Sum: 1
Current Number 2 Previous Number 1 Sum: 3
Current Number 3 Previous Number 2 Sum: 5
Current Number 4 Previous Number 3 Sum: 7
Current Number 5 Previous Number 4 Sum: 9
Current Number 6 Previous Number 5 Sum: 11
Current Number 7 Previous Number 6 Sum: 13
Current Number 8 Previous Number 7 Sum: 15
Current Number 9 Previous Number 8 Sum: 17
"""

#Q2 Write your program here.
print("Printing current and previous numbers and their sum in a range of 9")
sum = 0
num = [0,1,2,3,4,5,6,7,8,9]
for i in range(1,len(num)) :
  sum = num[i] + num[i-1]
  print("Current Number " + str(num[i]) + " Previous Number " + str(num[i-1]) + " Sum: " + str(sum))

"""**Question 3** (3 marks): Write a program in which you need to print ASCII characters according to the pattern shown in the image below. The user’s input number (e.g., 10) will decide how many lines you should print in your output. In this program, it should be noted that the output should start with  character A (65 in ASCII), and it is incremental (e.g., B=66, C=67). (Hint: to change from an ASCII code to a character, you may need to use chr(num) in your code). Also, you should note that when you display more than one character in the output, there should have a space between two characters (e.g., B(space)B).
Enter a number...:10
A
B B
C C C
D D D D
E E E E E
F F F F F F
G G G G G G G
H H H H H H H H
I I I I I I I I I
J J J J J J J J J J
"""

#Q3 Write your program here.

n = int(input("Enter a number...:"))
for i in range(n) :
  message = chr(65+i)+" "
  print((message*(i+1)).strip())