# -*- coding: utf-8 -*-
"""Copy of FinalPrep_Part2_ToStudent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QK55CIZJ5DBDJEACn5rMtuuUwoxHwm7G

# Final Preparation Part2
Objective: 


*   Lecture5: List Processing
*   Lecture6: Function
*   Lecture7: String Processing

<B>Question 1: (5 marks)<B> 

You have the following list:
"""

a1 = [["XOOXX"],["XXOXX"],["XXOXX"],["XOOOX"]]

"""Your task is to write a function to return a new list that removes the inner lists from a1. Therefore your resulting list from the function is 

"""

#["XOOXX","XXOXX","XXOXX","XOOOX"]

# [y for x in l for y in x]

"""Write the function in a code cell provided below: 

<B>Requirement: 
    
    - You must use list comprehension to produce the resulting list. You will not get any mark if you do not use list comprehension!
    
    - a1 can contain a list of any string, of any length (string length and list length can vary). Your code must work for every possible a1. If not, you get 0 mark.    
"""

a1 = [["XOOXX"],["XXOXX"],["XXOXX"],["XOOOX"]]


#You can use a1 as a global variable.
#Write your function below.
def yourFunction(a1) :
  return [x for i in a1 for x in i]




a2 = yourFunction(a1)
print(a2)

"""===================================================================

<B>Question 2: (15 marks)<B> 

You have the following list, a0 and a1, representing "0" and "1" in graphic form (shown in file numberplate.txt) 
    
Your task is to write a program that 
    
    - receives a series of "0" and "1", separated by space.  
    
    - Prints out the graphic form in sequence, according to the input sequence. 
     
<B>Requirement: 
    
    a0 and a1's graphic representations have equal width and height. But their width and height can be of any size. Your program must allow this. If not, you get 0 mark.  
    
    Example execution is shown in file Q2Example.png

**numberplate.txt**

a0

OOOOO

OXXXO

OXXXO

OOOOO


a1

XOOXX

XXOXX

XXOXX

XOOOX

run
1 0 1
XOOXX OOOOO XOOXX
XXOXX OXXXO XXOXX
XXOXX OXXXO XXOXX
XOOOX OOOOO XOOOX

run
0 1 0 0 1 1
OOOOO XOOXX OOOOO OOOOO XOOXX XOOXX
OXXXO XXOXX OXXXO OXXXO XXOXX XXOXX
OXXXO XXOXX OXXXO OXXXO XXOXX XXOXX
OOOOO XOOOX OOOOO OOOOO XOOOX XOOOX

run
1 1 0 0 1 0 1 0
XOOXX XOOXX OOOOO OOOOO XOOXX OOOOO XOOXX OOOOO
XXOXX XXOXX OXXXO OXXXO XXOXX OXXXO XXOXX OXXXO
XXOXX XXOXX OXXXO OXXXO XXOXX OXXXO XXOXX OXXXO
XOOOX XOOOX OOOOO OOOOO XOOOX OOOOO XOOOX OOOOO
"""

a0 = ["OOOOO","OXXXO","OXXXO","OOOOO"]
a1 = ["XOOXX","XXOXX","XXOXX","XOOOX"]

#Write your code below
order = [str(e) for e in input().split()]
message = ""

for j in range(len(a0)) :
  message = ""
  for i in order :
    if i == "1" :
      message += a0[j]
    elif i == "0" :
      message += a1[j]
    message += " "
  print(message.strip())