# -*- coding: utf-8 -*-
"""Copy of Repetition_ImagesFromDrive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bN9rOvmYuGKJPCoD4p-u8dq3EEZcx3HT

# Repetition (Loop)

## Topics
* Recap about flowchart
* while loop
* for loop
    -  for k in range(…)
    -  for ch in setting
    -  for elem in a_list
* break
* nested loop

## Recap about flowchart

In general, there are three types of flowchart control structure, sequential, selection, and repetition.
<img src="https://drive.google.com/uc?id=1Wgmm-ZFNh-BHj2lgo9xyfnkccps-gZQy" width="700px" />

## while loop

<img src="https://drive.google.com/uc?id=16M_85K1N5SjS2f1wZeJPW4QXM2NCdceg" width="600px" />

### while loop: Example 1 - Calculate a summation
<img src="https://drive.google.com/uc?id=1n2gWMq0K6mT66KE8rLByrg3vZan25oVa" width="600px" />

Try the following codes
"""

# This code assign s with 0, then, update s line by line and pring s out at the end. 
s = 0
s += (2*0 - 1)**2 # s = s + (2*0 - 1)**2
print(s)
s += (2*1 - 1)**2 # s = s + (2*1 - 1)**2
print(s)
s += (2*2 - 1)**2 # ...
print(s)
s += (2*3 - 1)**2
print(s)
s += (2*4 - 1)**2
print(s)

# This code produces the same result as above with allows us to easily specify the multiplication factor (k) 
# of s at the beginning of the code.

s = 0; k = 0
s += (2*k - 1)**2; k += 1
print(s)
s += (2*k - 1)**2; k += 1
print(s)
s += (2*k - 1)**2; k += 1
print(s)
s += (2*k - 1)**2; k += 1
print(s)
s += (2*k - 1)**2; k += 1
print(s)

# This code produces the same result as above but even more concise with the use of while loop.
s = 0; k = 0

while k < 5 :
	s += (2*k -1) **2 # s = s + (2*k -1) **2
	print(s)
	k += 1
print(s)

"""### while loop: Example 2 - Find the smallest among five numbers

Try the following codes
"""

# Without loop
# This following code reads five number from keyboard one by one without any loop. For each round, perform 
# a comparison with the current min (min_v), and update the min_v if the input value is smaller. 
# Print the smallest number out at the end of the code. 

min_v = float(input()) 	# get the first value
v = float(input())			# get the second value
if v < min_v:						# find the min value between the first and second values
	min_v = v
v = float(input()) 	# get the third value
if v < min_v:				# find the min value between the current min and the third value
	min_v = v
v = float(input()) 	# get the fourth value
if v < min_v:				# find the min value between the current min and the fourth value
	min_v = v
v = float(input())	# get the fifth value
if v < min_v:				# find the min value between the current min and the fifth value
	min_v = v
print("min_v = ", min_v)

# This code produces the same result as above but more concise using while loop. 

min_v = float(input())
k = 0
while k < 4 :
	v = float(input())
	if v < min_v:
		min_v = v
	k += 1
print(" min = ", min_v)

"""### while loop: Practice 1 - Find the average among five numbers

<img src="https://drive.google.com/uc?id=1-OxHwqcdTJF1y2Ww7phR6lBI6cw5onx3" width="300px" />
"""

# Write your code here!!!!! 
# You need to produce the output, which corresponds to its input. 
a = []
sum = 0
while True :
  if input() == "q" :
    break
  else :
    a.append(input())
for i in range(0,len(a)) :
  sum += float(a[i])
print(sum/len(a))

"""### while loop: Example 3 - Find a square root using bisection method

<img src="https://drive.google.com/uc?id=1TbwAtTWmJ1jm8dkcU-IClg4vn24InL6p" width="550px" />

Try the following codes
"""

# This code shows how to find the square root of a using the bisecion method.
# The while condition in this code directly compares between the targeted and calculated values (a and x**2).

a = float(input())
L = 0; U = a
x = (L + U)/2
while x**2 != a:
	if x**2 > a:
		U = x
	else:
		L = x
	x = (L + U)/2

print(x)

# This code changes the while condition to allow the difference of the targeted and calculated values (a and x**2)
# based on the epsilon. 
# if the absolute value between a and x**2 is less than epsilon, it assumes that the values of a and x** 
# are the same. 

epsilon = 1e-9   # 0.000000001
a = float(input())
L = 0; U = a
x = (L + U)/2
while abs(a-x**2) > epsilon:
	if x**2 > a:
		U = x
	else:
		L = x
	x = (L + U)/2

print(x)

"""## for loop

<img src="https://drive.google.com/uc?id=1FOszjt1ScpWrIBFzn5egMaxTcKNa82yG" width="500px" />

**for loop : form 1 - for k in range(start, stop, step)**

<img src="https://drive.google.com/uc?id=1VL5oPGwrw-bqtVAQ_-jIQYReLGPhizRq" width="400px" />

<img src="https://drive.google.com/uc?id=1695-ZzjlCbgzr3CLTteaZLNXhgSxwz-X" width="500px" />

**Differences between while and for loops**

<img src="https://drive.google.com/uc?id=1NsjKig_Uls2CHpPcvOHz7ZFlrahdy1to" width="500px" />

### for loop: Example 1 - find $\mu$ and $\sigma$

<img src="https://drive.google.com/uc?id=1B7KQ5Yrz336Ma_tmDjSYFzt52kgniaL4" width="200px" />

Try the following codes
"""

# This code gets the N numbers from keyboard, one by one. 
# Then, calculate mean and standard deviation of these N numbers.

N = int(input())
x = [0.0]*N
for i in range(N):
	x[i] = float(input())

s = 0
for i in range(N):
	s += x[i]
mean = s/N

s2 = 0
for i in range(N):
	s2 += (x[i]-mean)**2
sd = (s2/N)**0.5

print(mean, sd)

"""### for loop: Example 2 - Dot Product between u and v"""

# This code gets u as a string of numbers separated by space from keyboard: 
# Example input: 
# u : 1 2 0 2 1
# v : 2 2 1 2 2
# Then, calculate the dot product between u and v and print out the result.

x = input().split()
u = [0.0]*len(x)
for i in range(len(x)):
	u[i] = float(x[i])

x = input().split()
v = [0.0]*len(x)
for i in range(len(x)):
	v[i] = float(x[i])

dot = 0
for i in range(len(x)):
	dot += u[i]*v[i]

print(dot)

"""### for loop: Practice 1 - Check if the answer is correct

<img src="https://drive.google.com/uc?id=1Koa1YX2l5qRvxmY8AZAGRkFdO9X6dN5G" width="500px" />
"""

# Write your code here!!!!! 
# Example input =>
# sol input will be ABBBAAABCCBABABDCCDA
# ans input will be ABBBAABBCCBABABDCDDB
# Expected output => "17/20 correct answers."
# If the string lengths are not equal => "Incompatible!"
key = input()
ans = input()
count = 0
if len(key) != len(ans) :
  print("Incompatible!")
else :
  for i in range(len(key)) :
    if key[i] == ans[i] :
      count += 1
  print(str(count)+"/"+str(len(key)),"correct answers.")

"""**for loop : form 2 - for c in a_string**

<img src="https://drive.google.com/uc?id=1KGLg_cnHtFF8_v_8QhURs7Bnk8SrHTK-" width="400px" />

### for loop: Example 3 - count number of digits in a string

Try the following codes
"""

# This code counts the number of digits appear in a string.
# Example of input: Hello2123BD
# Expected output will be 4, counted by 2, 1, 2, 3

# Approach 1
s = input()
digit_counts = 0
for ch in s:
	if "0" <= ch <= "9":
		digit_counts += 1
print(digit_counts)

# This code produces the same result as above but accessing each character within string s via indexing. 

s = input()
digit_counts = 0
for i in range(len(s)):
	if "0" <= s[i] <= "9":
		digit_counts += 1
print(digit_counts)

"""### for loop: Example 4 - remove all ( [ { } ] ) from an input string

Try the following codes
"""

s = input()
result = ""
for ch in s:
	if ch not in "([{}])":
		result += ch
print(result)

"""### for loop: Practice 2 - Construct a new string, replace ( ) with [ ] and vice versa.

<img src="https://drive.google.com/uc?id=1F5-G3qsSTCBfs1q326X_LQXhkdMz6AD7" width="500px" />
"""

# Write your code here!!
# Example of input: [x + (y – z)]
# expected output: (x + [y – z])
# Example of input: Programming
# expected output: Programming
s = input()
arr = list(s)
for i in range(0,len(arr)) :
  if arr[i] == "(" :
    arr[i] = "["
  elif arr[i] == ")" :
    arr[i] = "]"
  elif arr[i] == "[" :
    arr[i] = "("
  elif arr[i] == "]" :
    arr[i] = ")"
print("".join(arr))

"""**for loop : form 3 - for c in a_list**

<img src="https://drive.google.com/uc?id=1xhQQ3c85TttIHXLQLk2Cpa15WGGs7gjT" width="500px" />

### for loop: Example 5 - find an average

Try the following codes
"""

# This code gets a list of numbers (all numbers are on the same line and separated by space)
# Example input: 10 20 30 20 10
# expected output: Average =  18.0

x = input().split()
s = 0
for e in x:
	s += float(e)
avg = s/len(x)
print("Average = ", avg)

"""<img src="https://drive.google.com/uc?id=1SrJ1j6gvT_tUdQgQlGtKkZINiqXJ7I7g" width="500px" />

### for loop: Practice 3 - count the number of "the" and "The"

<img src="https://drive.google.com/uc?id=1AtA1kYzCKE7F2Lwko34uS38QdAVXwPzH" width="500px" />
"""

# Write your code here!! for count the number of "the" and "The" within an input sentence. 
s = input()
r = ""
for ch in s :
  if ch not in "),('[].\"":
    r += ch
arr = r.split()
count = 0
for i in range(len(arr)) :
  if arr[i] == "The" or arr[i] == "the" :
    count += 1
print(count)

"""## Using the break

<img src="https://drive.google.com/uc?id=1PeG5anHPpAqoTtCN88sHuumc8OYlxqh5" width="500px" />

### break: Example 1 - get out of for loop

<img src="https://drive.google.com/uc?id=1btj6ZmhUWEz-V17JTFnTXBgetLS0PW-B" width="500px" />
"""

# This code gets a number (as intger) from keyboard, and then check if it is a prime number or not. 

n = int(input())
for k in range(2, n+1):
	if n%k == 0:
		break
if k == n:   
	print("Prime")
else:
	print("Composite")

"""### break: Example 2 - get out of while loop

<img src="https://drive.google.com/uc?id=1GDBNZvvgjrsMz82IDla4wKD-ECVlCLlL" width="500px" />
"""

# This cods finds an average of the input numbers one by one with the condition to stop getting more 
# if current input is "q". Then, calculate the average and print out. 

t = input()
s = 0; n = 0
while t != "q":
	s += float(t)
	n += 1
	t = input()
print("Average =", s/n)

# This code produces the same result as above but using break to get out of the loop instead. 

s = 0; n = 0
while True:
	t = input()
	if t == "q":
		break
	s += float(t)
	n += 1
print("Average =", s/n)

"""### break: Practice 1 - guess number game

<img src="https://drive.google.com/uc?id=1_q4617DcMCov4HZ74urVaM4J8UI8syZs" width="550px" />
"""

# Write your code here!!. Some initial instructions are given...
# The code will gets a gussed number from keyboard and compared with the n, which randomly generated with in
# the prograam. 

# Hint: You can try to use break!!

import random

print("Guess my number (0 to 99)")
print("You have seven tries")
n = random.randint(0,99)
for k in range(7):
	m = int(input())
	if m < n :
		print("Higher")
	elif m > n :
		print("Lower")
	elif m == n :
		print("You win")
		break
	if k == 6 :
		print("You lose, the number is",str(n))

"""## Acitivities

### Activity 1-1: Write the code that corresponds to the flowchart.

<img src="https://drive.google.com/uc?id=1RA7Zrul2xyFB1P0wBkynwUDosyf3Sq2A" width="250px" />
"""

# Write your code here for Activity 1-1
n = int(input())
c = 0
while n > 0 :
  n //= 2
  c+= 1
print(c)

"""### Activity 1-2: Write the code that corresponds to the flowchart.

<img src="https://drive.google.com/uc?id=170P3O9uMn6Cg1M6RSIW7dLSUrZaxX_K9" width="350px" />
"""

# Write your code here for Activity 1-2
b = input() #must be an integer 
n = len(b)
d = 0
k = 0
while k < n :
  d += (2**k)*(int(b[n-k-1]))
  k += 1
print(d)

"""### Activity 1-3: Write the code that corresponds to the flowchart.

<img src="https://drive.google.com/uc?id=1BdkmmOtTPkAXPdPWNxQhXIBe9csAvzx8" width="300px" />
"""

# Write your code here for Activity 1-3
n = int(input())
c = 0
while n > 0 :
  n = n - 1
  if n%3 == 0 :
    n = n - c
    c += 1

"""### Activity 2-1: while loop - Read an integer n from keyboard, print out all odd numbers that are between 0 and n-1. """

# Write your code here for Activity 2-1

"""### Activity 2-2: while loop - Read integers from keyboard, first line will be integer n specifying more n lines of data to read on, calculate the average of these n numbers, print out the average. """

# Write your code here for Activity 2-2
# first line must be an integer. Other lines must be floating point numbers

"""### Activity 2-3: while loop - Read an integer from keyboard line by line, if the input integer is negative, print out the summation of all previously read positive integers. """

# Write your code here for Activity 2-3
# input can only be integers

"""### Activity 2-4: while loop - Read an integer from keyboard line by line, when encounted "end" from input then, print out the summation of all previously read integers. """

# Write your code here for Activity 2-4
# input can only be an integer or the word "end"

"""### Activity 2-5: while loop - Read integer n from keyboard, calculate the summation using the following equation : $$\sum_{i=1}^{n} i^{5}$$"""

# Write your code here for Activity 2-5

"""### Activity 2-6: while loop - Read a string t from keyboard, then, count the number of vowels (including both small and capital letters) in t and print out the result. """

# Write your code here for Activity 2-6

"""### Activity 3-1: close enough - Read real numbers a, b, and ep within the same line from input, print out "close enough" if  |a - b| <= ep * max(|a|, |b|) """

# Write your code here for Activity 3-1

"""### Activity 3-2: close enough - Read real number x from input, find $\sqrt[3]{x}$ assuming a, b are close enough when  |a - b| <= 1e-6 * max(|a|,|b|)"""

# Write your code here for Activity 3-2

"""### Activity 4-1: flowchart for loop - Write the code that corresponds to the flowchart.

<img src="https://drive.google.com/uc?id=14-6a9puy5hmRpyQ6qcMdAv4HftYbKN1V" width="275px" />
"""

# Write your code for Activity 4-1

"""### Activity 4-2: flowchart for loop - Write the code that corresponds to the flowchart.

<img src="https://drive.google.com/uc?id=1Q92tMdwIeDa_sWait2iFYTLGbJ3AVwQ_" width="275px" />
"""

# Write your code for Activity 4-2

"""<img src="https://drive.google.com/uc?id=1JCwtv4lGvjVrC62dPYUT-slLgYMBmOZp" width="275px" />"""

# Write your code for Activity 4-3

"""### Activity 5-1: for loop with string - Write the code that corresponds to the flowchart.

<img src="https://drive.google.com/uc?id=1AVc3vPhgM4l8T40MJWwJwPoe5lNGC7mC" width="275px" />
"""

# Write your code for Activity 5-1

"""### Activity 5-2: for loop with string - Write the code that corresponds to the flowchart. Also, try to explain what the flowchart represents

<img src="https://drive.google.com/uc?id=1xZ070OWgT5BN9YxLalY9wAI3GfFZVgb9" width="275px" />
"""

# Write your code for Activity 5-2

"""### Activity 5-3: for loop with string - Read a string from input one line, then, print out only the alphabet read from the string from left to right, one alphabet per line. For example, if the read string is "A-B-123 C" the print out will be A, B, and C in three consecutive lines. """

# Write your code for Activity 5-3

"""### Activity 5-4: for loop with string -  Read a strng from input one line, print out only the characters in the string with the odd position (position starts from 1), one character per line. For example, if the read string is "*ABCDE*", the print out will be A, C, and E in three consecutive lines. """

# Write your code for Activity 5-4

"""### Activity 5-5: for loop with string -  Read a stirng from input one line, print out each chracter in the string, one character per line. """

# Write your code for Activity 5-5

"""### Activity 6-1: for e in list - Read product IDs read from input as A1023 P223 A392, write a python code to print out each product ID, one ID per line. """

# Write your code for Activity 6-1

"""### Activity 6-2: for e in list - Read product category with colon and a list of product IDs as "Office Product : A1023 P223 A392" from key board, write a python code to print out each product ID from *right to left*, one ID per line."""

# Write your code for Activity 6-2

"""### Activity 6-3: for e in list - Read a string from keyboard and use split() on this string and assign the result to x. Read another string from keyboard and assign this string to a. Write a python code to count the number of string in a appeared in x. """

# Write your code for Activity 6-3
x = input().split()
a = input()

"""### Activity 7-1: Break - Write the code that corresponds to the following flowchart. The input from keyboard is an integer.

<img src="https://drive.google.com/uc?id=1JiCXSY6scVRjCSAp_6HuVNcsKr6RyS-d" width="200px" />
"""

# Write your code for Activity 7-1

"""### Activity 7-2: Break - Write the code that corresponds to the following flowchart. The input from keyboard is an integer.

<img src="https://drive.google.com/uc?id=1cKht6qJrTXj4XGBJE7x8I65vJlMYNsmD" width="200px" />
"""

# Write your code for Activity 7-2

"""### Activity 7-3: Break - Read a string from keyboard and divide the string into substring by one of the following delimiter: "@", ":", "+", "-" For example, string abc@def can be printed out as abc and def, one substring per line. """

# Write your code for Activity 7-3

